# Generated by Django 5.1.6 on 2025-02-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'تخصص', 'verbose_name_plural': 'تخصص\u200cها'},
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='speciality',
        ),
        migrations.AddField(
            model_name='speciality',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='تخصص'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speciality',
            name='count',
            field=models.IntegerField(default=0, verbose_name='تعداد پزشکان'),
        ),
    ]
