# Generated by Django 5.1.6 on 2025-02-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_module', '0002_alter_speciality_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=100, verbose_name='تخصص'),
        ),
    ]
