# Generated by Django 5.1.6 on 2025-02-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_module', '0003_alter_speciality_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant', models.CharField(blank=True, choices=[('پزشک عمومی', 'پزشک عمومی'), ('متخصص', 'متخصص'), ('روانشناس', 'روانشناس')], max_length=100, null=True, verbose_name='دسته بندی')),
                ('count', models.IntegerField(default=0, verbose_name='تعداد پزشکان')),
            ],
        ),
    ]
