# Generated by Django 5.1.6 on 2025-02-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_module', '0004_consultant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultant',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
