# Generated by Django 5.1.6 on 2025-03-02 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home_module', '0020_doctors_degree_name'),
        ('Main_module', '0006_delete_consultant_delete_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='تعداد تخصص')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_module.degree', verbose_name='تخصص')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'تخصص ها',
            },
        ),
    ]
