# Generated by Django 5.1.6 on 2025-03-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_module', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=100, verbose_name='تخصص'),
        ),
    ]
