# Generated by Django 5.1.6 on 2025-02-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0002_alter_user_options_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=120),
        ),
    ]
