# Generated by Django 5.1.6 on 2025-02-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0006_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'دکتر', 'verbose_name_plural': 'دکترها'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'تایم ویزیت', 'verbose_name_plural': 'تایم های ویزیت'},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day',
            field=models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنج\u200cشنبه'), ('friday', 'جمعه')], default=None, max_length=9),
            preserve_default=False,
        ),
    ]
