# Generated by Django 5.1.6 on 2025-02-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0007_alter_doctors_options_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.CharField(blank=True, choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنج\u200cشنبه'), ('friday', 'جمعه')], max_length=9, null=True),
        ),
    ]
