# Generated by Django 5.1.6 on 2025-02-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0008_alter_timeslot_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنج\u200cشنبه'), ('friday', 'جمعه')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='day',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='days',
            field=models.ManyToManyField(to='Home_module.dayofweek'),
        ),
    ]
