# Generated by Django 5.1.6 on 2025-02-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0009_dayofweek_remove_timeslot_day_timeslot_days'),
        ('Main_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='speciality',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='Main_module.speciality', verbose_name='تخصص'),
        ),
    ]
