# Generated by Django 5.1.6 on 2025-02-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0011_doctors_speciality_name_alter_doctors_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مدرک'),
        ),
    ]
