# Generated by Django 5.1.6 on 2025-02-15 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0013_remove_doctors_degree_doctors_consultant'),
        ('Main_module', '0004_consultant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main_module.consultant', verbose_name='دسته بندی'),
        ),
    ]
