# Generated by Django 5.1.6 on 2025-02-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0014_alter_doctors_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='degree',
            field=models.CharField(blank=True, choices=[('پزشک عمومی', ''), ('متخصص', ''), ('phd', ''), ('کارشناسی ارشد', ''), ('کارشناسی', ''), ('دستیار تخصصی', '')], max_length=100, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='id_code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='sex',
            field=models.CharField(blank=True, choices=[('men', 'مرد'), ('women', 'زن')], max_length=100, null=True, verbose_name='جنسیت'),
        ),
    ]
