# Generated by Django 5.1.6 on 2025-02-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0015_doctors_birthday_doctors_degree_doctors_id_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='main_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره مطب'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='شماره نظام پزشکی'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='speciality_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تخصص پزشک'),
        ),
    ]
