# Generated by Django 5.1.6 on 2025-02-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0016_doctors_last_name_alter_doctors_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('پزشک عمومی', 'پزشک عمومی'), ('متخصص', 'متخصص'), ('phd', 'PhD'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('کارشناسی', 'کارشناسی'), ('دستیار تخصصی', 'دستیار تخصصی')], max_length=100, unique=True, verbose_name='مدرک تحصیلی')),
            ],
            options={
                'verbose_name': 'مدرک تحصیلی',
                'verbose_name_plural': 'مدارک تحصیلی',
            },
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='speciality',
        ),
    ]
