# Generated by Django 5.1.6 on 2025-02-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0017_degree_remove_doctors_consultant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='رشته پزشکی')),
                ('degrees', models.ManyToManyField(related_name='specialties', to='Home_module.degree', verbose_name='مدرک\u200cهای تحصیلی')),
            ],
            options={
                'verbose_name': 'رشته پزشکی',
                'verbose_name_plural': 'رشته\u200cهای پزشکی',
            },
        ),
    ]
