# Generated by Django 5.1.6 on 2025-02-18 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0018_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home_module.degree', verbose_name='مدرک تحصیلی'),
        ),
    ]
