# Generated by Django 5.1.6 on 2025-02-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0019_alter_doctors_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='degree_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مدرک'),
        ),
    ]
